# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd48079fb9446332e00d589021e676f6a62e5c1f2168929bb657d53068976ffca765ea3a64a5f9fda5c2cde34b4ee0554d11b6cd83c27ad4409a0a89bd9a9043

test:
  secret_key_base: 4d3ff0d72b3b5eb987d3573d04b0ea12fc0efd31518687e5b2d5bc38fef08b00b21a8c335af9a0423136ff893f96d2453d8a64e17cfe5f5b58b96872cc9ee372

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
